image: node:lts-buster

stages:
  - Build
  - Publish

build:
  stage: Build
  script:
    - npm install
    - npm run build
    - npm pack
    - tar -tf *.tgz | sort
    - test -z "$(git status --porcelain)" || (git status; false)
  artifacts:
    when: on_success
    paths:
      - "bity-oauth2-auth-code-pkce-*.tgz"

publish:
  stage: Publish
  only:
    refs:
      - tags
  script:
    - npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
    - npm publish "bity-oauth2-auth-code-pkce-${CI_COMMIT_TAG}.tgz"
  when: manual
